node {
    def server = Artifactory.server 'artifactory'
    def rtMaven = Artifactory.newMavenBuild()

    stage ('Clone') {
        git url: 'https://github.com/malkinfedor/java_hello_servlet.git'
    }

    stage ('Get data from Git commit'){
        sh 'cd "${WORKSPACE}"; /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/mvn_3.5.4/bin/mvn clean install; echo $git.dirty' 
        
        sh 'git checkout remotes/origin/misc'
        GIT_HASH = sh (
        
        script: '${WORKSPACE}/misc/getHashAndDate.sh hash',
        returnStdout: true
        ).trim()
        echo "Git commit hash: ${GIT_HASH}"
        
        GIT_DATE = sh (
        script: '${WORKSPACE}/misc/getHashAndDate.sh date',
        returnStdout: true
        ).trim()
        echo "Git commit hash: ${GIT_DATE}"
        sh 'git checkout master'
    }
  
    stage('publish') {
    
    // to run readMavenPom need to install the pipeline-utility-steps plugin
    def pom = readMavenPom file: 'pom.xml'
    def uploadSpec = """{
      "files": [
        {
          "pattern": "${WORKSPACE}/target/*.war",
          "target": "asusin_app_test-snapshot/com/geekcap/vmturbo/hello-world-servlet-example/${GIT_DATE}-${GIT_HASH}/${pom.artifactId}-${GIT_DATE}-${GIT_HASH}.war"
        },
        {
          "pattern": "${WORKSPACE}/pom.xml",
          "target": "asusin_app_test-snapshot/com/geekcap/vmturbo/hello-world-servlet-example/${GIT_DATE}-${GIT_HASH}/${pom.artifactId}-${GIT_DATE}-${GIT_HASH}.pom"
        }
     ]
    }"""
    server.upload(uploadSpec)
    echo env.WORKSPACE
  }
  
}
