FROM tomcat
RUN wget http://ansibleclient.westus.cloudapp.azure.com:8082/artifactory/asusin_app_test-release/com/geekcap/vmturbo/hello-world-servlet-example/0.3/hello-world-servlet-example-0.3.war && cp hello-world-servlet-example-0.3.war /usr/local/tomcat/webapps/helloworld.war
#ADD deploy /usr/local/tomcat/webapps
